webtalk_init -webtalk_dir C:/Users/Noman Traders/Desktop/habib/CA/RISC-V-pipelined-processor/task_2_pipelined_with_hazards/pipelined_with_hazards/pipelined.sim/sim_1/behav/xsim/xsim.dir/RISC_V_PIPELINED_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 22 13:23:02 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "295e45a1-9498-4cf7-994b-2c45dbc7b516" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5391ecc671b54515a27b28db822d146a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "19" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "124 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "13 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "201" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "22" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "68936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1118997833 -regid "" -xml C:/Users/Noman Traders/Desktop/habib/CA/RISC-V-pipelined-processor/task_2_pipelined_with_hazards/pipelined_with_hazards/pipelined.sim/sim_1/behav/xsim/xsim.dir/RISC_V_PIPELINED_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Noman Traders/Desktop/habib/CA/RISC-V-pipelined-processor/task_2_pipelined_with_hazards/pipelined_with_hazards/pipelined.sim/sim_1/behav/xsim/xsim.dir/RISC_V_PIPELINED_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Noman Traders/Desktop/habib/CA/RISC-V-pipelined-processor/task_2_pipelined_with_hazards/pipelined_with_hazards/pipelined.sim/sim_1/behav/xsim/xsim.dir/RISC_V_PIPELINED_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
